### ISSUE TITLE
Probleme mit eingebetteter Schriftart

### ISSUE THREAD

**Issue by MartinBoehmer** [jonas-koeritz/Taktische-Zeichen#1]
Bei der testweisen Verwendung der SVG-Dateien in draw.io und inkscape 0.92.1 unter Windows habe ich zwei Probleme mit den SVG-Dateien und der Einbettung der Schriftart:

1. Fehlende CDATA-Auszeichnung des inline CSS
2. Name der Schriftart entspricht nicht dem in der TTF gespeicherten Namen "LubalGraph Bd BT"

Die Änderungen in der beigefügten SVG-Datei lösen die Probleme bei mir. Wäre toll, wenn alle SVG-Dateien derart angepasst werden könnten.

[EAL.zip](https://github.com/jonas-koeritz/Taktische-Zeichen/files/847371/EAL.zip)

**Comment by jonas-koeritz** [comment]
Darf ich fragen wofür du die Symbole verwenden willst?

**Comment by MartinBoehmer** [comment]
Danke für die schnelle Überarbeitung.

Ich versuche mit deinen Symbolen eine Reihe von Bibliotheken mit taktischen Zeichen zur Verwendung in draw.io zu erstellen. draw.io ist praktisch ein webbasiertes MS Visio.
Damit sollen dann taktische Karten erstellt werden. Die Bibliotheken würde ich auch quelloffen bei Github einstellen.

Für meine Zwecke fehlen aber noch diverse Zeichen. Ich hoffe, dein Angebot, weitere Zeichen zu erstellen, steht noch? Ich würde dann Issues dafür aufmachen. Es wären ca. 20 Stück.

**Comment by jonas-koeritz** [comment]
Klar erstelle Ich auch noch weitere Zeichen. Die Issues kannst du gerne auf machen!
