### ISSUE TITLE
Richtige Anwendung der CC-BY Lizenz durch Nutzer/innen

### ISSUE THREAD

**Issue by dmth** [jonas-koeritz/Taktische-Zeichen#102]
In #90 wurde eine neue Lizenz festgelegt. Das ist gut so.

Derzeit arbeite ich an einen größeren Kommunikationsplan und nutze die Zeichen die mit dem Repo hier generiert wurden.

Jetzt habe ich das Problem, wie ich auf dem Kom-Plan die CC-BY Lizenz korrekt unterbringe.
Eine Notiz "CC-BY Jonas Köritz" würde die anderen Kontributoren außer acht lassen.

Vorschlag: "CC-BY  https://github.com/jonas-koeritz/Taktische-Zeichen/blob/master/Contributors"

Das macht dann aber das File "Contributors" notwendig, in dem alle gelistet werden. Alternativ den Link auf das von Gitgub generierte https://github.com/jonas-koeritz/Taktische-Zeichen/graphs/contributors 

Dann fallen aber die Leute hinten runter, die mal einen Patch per Mail eingeschickt haben, oder deren Code anderweitig eingepflegt wurde.

Wie ist eure Meinung dazu?

**Comment by jonas-koeritz** [comment]
Ich würde hier ähnlich wie OpenStreetmap einfach "Taktische-Zeichen und Unterstützer" nehmen, allerdings ist die "nötige schöpferische Höhe" bei den Zeichen vermutlich nicht erreicht, daher kann man den Hinweis auch weg lassen.

Ich selbst verfolge definitiv nicht die Absicht das ab zu mahnen oder ähnliches. ;)

Wenn alles nix hilft dann geht das Ding hier bald in die Beer License! 🍺

**Comment by Daugl** [comment]
Die Schöpfungshöhe sehe ich wie Jonas als nicht erreicht, vor Allem da diese Zeichen größtenteils in verschiedensten DVs und Empfehlungen seit Jahrzehnten auftauchen.

Mir fallen zwei Möglichkeiten ein, wie das Problem mit der Namensnennung behoben werden kann:
1. Anpassen der Lizenz, die für verschiedene Fälle (wie z.B. ein Kommunikationsplan, oder nicht kommerzielle Nutzung) auf die Namensnennung verzichtet, oder 
2. Das Entlassen in die die Lizenz CC0 und damit in die public domain.
