### ISSUE TITLE
Taktische Zeichen Truppführer Fg N fehlt 

### ISSUE THREAD

**Issue by nc-haszloja** [jonas-koeritz/Taktische-Zeichen#105]
Dieses Template kann für die Anfrage eines neuen taktischen Zeichens genutzt werden. Für mehrere Zeichen sollten möglichst auch mehrere Issues erstellt werden.
Die genaue Bezeichung des Zeichens und möglichst auch ein Beispiel sollten Teil des Issues sein.
Wenn eine Normung/Dienstvorschrift/Vorgabe existiert, diese ebenfalls mit verlinken.

[URL zu einem Beispiel, möglichst als Bild](https://github.com/jonas-koeritz/Taktische-Zeichen)
[URL zur Dienstvorschrift](https://github.com/jonas-koeritz/Taktische-Zeichen)

**Comment by jonas-koeritz** [comment]
Ist bereits im Code vorhanden, es gibt nur noch kein Release mit fertigen Dateien.

https://www.github.com/jonas-koeritz/Taktische-Zeichen/tree/master/symbols%2FTHW_Personen%2FTruppf%C3%BChrer_N.j2
