### ISSUE TITLE
Zeichen des neuen FZ Führung/Kommunikation

### ISSUE THREAD

**Issue by apertsch** [jonas-koeritz/Taktische-Zeichen#119]
Neues Zeichen für den FZ FK wurde unter #89 erzeugt. 

Mit Veröffentlichung der StAN am 01.07.2021 sollten die taktischen Zeichen für die Gruppen und zugehöriges Führungspersonal ergänzt werden. Symbole ergeben sich logisch aus der Systematik, Abkürzung lt. StAN jeweils in Anführungszeichen angeführt

Einheiten
- Zugtrupp "FZ-FK" (Einheit ZTr ohne "Führungsbalken" oben)
- Stabspersonal "Stab" (Einheit ohne Größenzeichen, mit "Führungsbalken" oben) - Zeichen existiert als "BR_Stab", sollte zu "Stab" oder "FK_Stab" unbenannt werden
- FGr Führungsunterstützung "F" (Gruppe mit "Führungsbalken" oben)
- FGr Kommunikation "K", als Typ A und B (Gruppe ohne "Führungsbalken" oben)

Personen
- Zugführer "FK"
- Zugtruppführer "FK"
- Gruppenführer "F"
- Truppführer "F"
- Gruppenführer "K"
- Truppführer "K"
- Sachgebietsleiter: Person THW mit Führungsfunktion, Text "SGL" (in THW_Personen/Helfer_SGL.svg fehlt der Führungsbalken)
- Fachkraft IuK: Person THW ohne Führungsfunktion, Text "IuK"
- Maschinist/in Richtfunk: Person THW ohne Führungsfunktion, Text "RiFu" (nicht sicher, kein Symbol in StAN)
- Fernmeldeführer: Person THW mit Führungsfunktion, Text "FmFü"
- Leiter des Fernmeldebetriebs: Gruppenführer THW, Text "LdF" (GrFü F ist nun der LdF)

Fahrzeuge
- Mastkraftwagen: Fahrzeug normal (nicht geländegängig in StAN!?), "MastKW"
- Anhänger Spezialaufbau FGr K (1 t Nutzlast): Anhängersymbol THW mit Beschriftung "K"
- Anhänger (2 t Nutzlast): Anhängersymbol THW mit Beschriftung "2 t"
- Anhänger Richtfunktechnik (2 t Nutzlast): Anhängersymbol THW mit Beschriftung "RiFu"

StAN-Links:
- [ZTr FK](https://extranet.thw.de/SharedDocs/Downloads/THW-Extranet/DE/Service/STAN/stan_ztr_tz_2021.pdf?__blob=publicationFile)
- [FGr F](https://extranet.thw.de/SharedDocs/Downloads/THW-Extranet/DE/Service/STAN/stan_f_2021.pdf?__blob=publicationFile)
- [FGr K, Typ A](https://extranet.thw.de/SharedDocs/Downloads/THW-Extranet/DE/Service/STAN/stan_k_a_2021.pdf?__blob=publicationFile)
- [FGr K, Typ B](https://extranet.thw.de/SharedDocs/Downloads/THW-Extranet/DE/Service/STAN/stan_k_b_2021.pdf?__blob=publicationFile)
- [Stab](https://extranet.thw.de/SharedDocs/Downloads/THW-Extranet/DE/Service/STAN/stan_stab_2021.pdf?__blob=publicationFile)

**Comment by daBo-sh** [comment]
In Pull #123 sind folgende Zeichen enthalten:
ZTr, Stab, F, K(A/B)
ZF, ZTrFü, GrFü F/K, TrFü F/K
Anhänger K 1t, Anhänger 2t, MTW FGr

**Comment by daBo-sh** [comment]
Weitere Zeichen in Pull #125 
Nicht umgesetzt: - Leiter des Fernmeldebetriebs: Gruppenführer THW, Text "LdF" (GrFü F ist nun der LdF)

Da die FGr F einen GrFü hat und eine Zusatzfunktion LdF einem GrFü zugewiesen werden muss ergibt sich mMn implizit, dass der GrFü F zwangsweise immer der LdF sein muss.

Alle anderen Punkte sind umgesetzt.

**Comment by apertsch** [comment]
> Nicht umgesetzt: - Leiter des Fernmeldebetriebs: Gruppenführer THW, Text "LdF" (GrFü F ist nun der LdF)
> 
> Da die FGr F einen GrFü hat und eine Zusatzfunktion LdF einem GrFü zugewiesen werden muss ergibt sich mMn implizit, dass der GrFü F zwangsweise immer der LdF sein muss.

Hatte mir vorab ähnliche Gedanken gemacht, dachte dann aber "lieber ein Zeichen zuviel als eines zu wenig". Mit diesem Gedankengang würde ich dann aber ein normales Helfer-Zeichen mit "LdF" vorschlagen, falls die Zusatzfunktion im Einsatz (temporär) einem anderen Helfer übertragen bzw. von diesem wahrgenommen wird, wenngleich das nach der neuen StAN nicht vorgesehen ist.

**Comment by jonas-koeritz** [comment]
PR ist drin, erstmal schließe Ich hier :)
