### ISSUE TITLE
Fehlende Zeichen FZ Log

### ISSUE THREAD

**Issue by apertsch** [jonas-koeritz/Taktische-Zeichen#122]
Folgende Zeichen für den FZ Log scheinen zu fehlen:

- Zugführer "Log"
- Zugtruppführer "Log"
- Gruppenführer "Log-MW"
- Gruppenführer "Log-VG"
- Truppführer "Log-VG"
- Beim Truppführer "Log-V" fehlt der Bindestrich
- Logistikführer: Person THW mit Führungsfunktion, Text "LogFü"
- Anhänger mit Spezialaufbau für FGrLog-V, Kühl: Anhänger THW Text "Kühl"
- Werkstattcontainer: Abrollbehälter Container THW, Text "Wks"
- Anhänger Plattform: Beispiel siehe [StAN Log-MW 2021](https://extranet.thw.de/SharedDocs/Downloads/THW-Extranet/DE/Service/STAN/stan_log_mw_2021.pdf?__blob=publicationFile), S. 7

[StAN 2021](https://extranet.thw.de/THW-Extranet/DE/Service/STAN/stan_node.html)

**Comment by jonas-koeritz** [comment]
PR ist drin, erstmal zu.
