### ISSUE TITLE
FZ FK

### ISSUE THREAD

**Issue by jensmaucher** [jonas-koeritz/Taktische-Zeichen#127]
Bei den Einheiten fehlt der THW Fachzug FK

**Comment by jonas-koeritz** [comment]
Das Zeichen ist im Code schon erstellt. Nur ein aktuelles Release mit diesem Zeichen gibt es noch nicht, Ich lasse mal ein Release durchlaufen, danach steht dann der Satz mit diesem Zeichen zur Verfügung.
