### ISSUE TITLE
Typo Wasserretttung :-)

### ISSUE THREAD

**Issue by white-gecko** [jonas-koeritz/Taktische-Zeichen#129]
Sehr schick, aber ich glaub es wird Wasserrettung geschrieben, auch wenn es etwas mit Schifffahrt zu tun hat :-)

https://github.com/jonas-koeritz/Taktische-Zeichen/tree/master/symbols/Wasserretttung_Einheiten

**Comment by jonas-koeritz** [comment]
Der war mir auch schon aufgefallen. Danke für den Hinweis!
