### ISSUE TITLE
Lager- und Transportcontainer (FB) THW

### ISSUE THREAD

**Issue by white-gecko** [jonas-koeritz/Taktische-Zeichen#131]
Lager- und Transportcontainer THW fehlt

https://thwiki.org/t=Fachgruppe_Notversorgung/Notinstandsetzung

**Comment by jonas-koeritz** [comment]
In THW-Blau enstpricht das Zeichen exakt "THW_Fahrzeuge/Abrollbehälter_Container". Ich gehe mal davon aus dass das Zeichen im THWiki ein Platzhalter ist?

**Comment by jonas-koeritz** [comment]
Falls das Zeichen nicht das ist was du gemeint hast, gerne wieder öffnen.

**Comment by white-gecko** [comment]
Ich denk auch, dass das ein Platzhalter ist, zumal es ja auch als Fremdbeschaffung/Finanzierungsbeschaffung angegeben ist.

**Comment by jonas-koeritz** [comment]
Fehlt dann noch ein Zeichen oder braucht es das nicht extra in der andere Optik?
