### ISSUE TITLE
Anpassung an Empfehlung des BBK

### ISSUE THREAD

**Issue by dstahlmann** [jonas-koeritz/Taktische-Zeichen#139]
Das Projekt finde ich super. Allerdings gibt es in der Darstellung eine Diskrepanz zwischen dem Status Quo im Projekt sowie der Empfehlung des Bundesamtes für Bevölkerungsschutz und Katastrophenhilfe (BBK) durch die Publikation "Empfehlungen für Taktische Zeichen im Bevölkerungsschutz" (Januar 2012, korrigierte zweite Auflage).

Die Darstellung der **Einheiten** wie sie ist, würde ich durchaus bevorzugen. Bei den **Personen** sollte der Empfehlung des BBK gefolgt werden: Einheitsführer haben ein schwarzes Dreieck in der Spitze. Vgl. hierzu "Empfehlungen für Taktische Zeichen im Bevölkerungsschutz", S. 18 & S. 19.

[Empfehlungen für Taktische Zeichen im Bevölkerungsschutz](https://www.kritis.bund.de/SharedDocs/Downloads/BBK/DE/Publikationen/Broschueren_Flyer/Empfehlungen_Takt_Zeichen_im_BevSch.pdf?__blob=publicationFile) (Januar 2012, korrigierte zweite Auflage)

**Comment by jonas-koeritz** [comment]
Die BBK Empfehlung so 100% ernst zu nehmen halte Ich aufgrund der recht dürftigen Beispiele im Dokument für schwierig. Schwarz auf rot als Standard für die Feuerwehrzeichen ist kaum lesbar.
Mit dem schwarzen Hut für Feuerwehr Führungskräfte kann Ich mich noch anfreunden, Ich denke aber in den meisten Fällen sollte die Lesbarkeit bevorzugt werden.
Auf Seite 10 wird außerdem explizit auch Weiß als Farbe für die Umrandung und die Texte auf Feuerwehrzeichen angegeben.

**Comment by jonas-koeritz** [comment]
Taktische Zeichen müssen aus meiner Sicht (und aus Sicht des BBK, um es dann selbst schlecht in den Beispielen vorzumachen) vor allem schnell und einfach zu lesen sein. Der fehlende Kontrast von schwarz auf rot ist da kontraproduktiv.
