### ISSUE TITLE
Fehlende THW-Fahrzeuge

### ISSUE THREAD

**Issue by KBreker** [jonas-koeritz/Taktische-Zeichen#141]
Ahoi!

Aus meiner Sicht fehlen noch folgende taktische Zeichen für THW-Fahrzeuge:

- LKW LdKr (nicht geländegängig), z.B. der FGr Öl
- WLF (nicht geländegängig), z.B. der FGr Öl
- Anhänger Wechselbrücke der Bergungsgruppe (sofern man nicht das allgemeine Symbol nutzen möchte)
- Anhänger Wechselladersystem, z.B. der FGr Öl

Gruß,

Kai

**Comment by daBo-sh** [comment]
Nach StAN hat die B einen Anhänger 7t, welcher Anhänger WB ist gemeint? Die N hat den Plattformanhänger, der ist ebenfalls drin.

**Comment by KBreker** [comment]
Ich meine diesen Anhänger Wechselbrücke, der in den letzten Jahren zahlreich ausgeliefert wurde:

https://ov-kiel.thw.de/unser-thw-ortsverband/einheiten-technik/bergungsgruppe/gkw-anh-wb/

zul. Gesamtgewicht: 18.000 kg
Leergewicht: 2.650 kg
Nutzlast: 15.350 kg

Damit verbunden die Frage, ob beim taktischen Symbol die Wechselbrücke extra gekennzeichnet werden soll.

**Comment by KBreker** [comment]
Danke, hast Du dann auch gleich ein taktisches Zeichen für die Wechselbrücke alleine erstellt? ;-)

**Comment by daBo-sh** [comment]
Nicht nötig, Abrollbehälter / Container gibt es in der Sammlung schon. Abrollcontainer, BDF- und ISO-Container werden alle durch das "Abrollbehälter-Symbol" dargestellt.
