### ISSUE TITLE
Fehlende Kommunal-Fahrzeuge

### ISSUE THREAD

**Issue by KBreker** [jonas-koeritz/Taktische-Zeichen#148]
Ahoi!

Bei den Kommunal-Fahrzeugen fehlen noch:

- Personenkraftwagen, geländegängig und nicht geländegängig
- Gabelstapler, geländegängig und nicht geländegängig
- Kettenfahrzeug allgemein, z.B. für Kettenbagger

**Comment by daBo-sh** [comment]
In #149 hinzugefügt
