### ISSUE TITLE
Fachzug FK

### ISSUE THREAD

**Issue by hbrueckl** [jonas-koeritz/Taktische-Zeichen#151]
Hi,
vielleicht könntest Du bei Gelegenheit die FGr FK in Fachzug FK ändern.
Danke
Heiko

**Comment by Daugl** [comment]
Hallo Heiko,
der Fachzug FK ist in den Zeichen vorhanden, ebenso wie die Fachgruppe FK.
"Veraltete" Einheiten werden nicht entfernt, um auch historische Lagen darstellen zu können.
