### ISSUE TITLE
NRW Brandschutz vervollständigen

### ISSUE THREAD

**Issue by LaGGi97** [jonas-koeritz/Taktische-Zeichen#158]
Aus den Konzepten des Landes NRW fehlen im Bereich Brandschutz noch folgende Zeichen:

- BEZIRKSABTEILUNG
- BEREITSCHAFT
- A-FÜHRUNG
- B-FÜHRUNG
- Logistikzug
- KdoW (Komandowagen)
- MTW

[Katastrophenschutz NRW: Brandschutz ](https://www.idf.nrw.de/service/downloads/pdf/interschutz_2015/medien_interschutz_poster_2_brandschutz_wasserrettung.pdf)

**Comment by jonas-koeritz** [comment]
Moin,

Die Bezeichnungen für "A-Führung" und "B-Führung" kommen mir ein bisschen ungewöhnlich vor, das Zeichen dazu wird aber gefühlt auch nirgends, außer auf diesem Poster verwendet. Gibt es dazu noch weitere Quellen (Ausbildungsunterlagen o.ä.)?

**Comment by LaGGi97** [comment]
Moin! Ich finde tatsächlich auch nichts wo diese Bezeichnung verwendet wird.
Ich denke gemeint sind damit 

- Bezirksabteilungsführung (BezAbtFü)  = A(bteilungs)-Führung
- Bezirksbereitschaftsführung (BezBerFü)  = B(ereitschafts)-Führung 
 
Hier Seite 7 und 10: 
https://lernkompass.idf.nrw/goto.php?target=file_336_download&client_id=Feuer

**Comment by jonas-koeritz** [comment]
In dem Poster sind dann wohl einfach die falschen Symbole...Ich hab jetzt mal die Varianten aus dem Lernmaterial genommen
![Bezirksabteilungsführung](https://github.com/user-attachments/assets/a4661cc8-c07d-40a1-808e-0ebfc5f7ef90)
![Bezirksbereitschaftsführung](https://github.com/user-attachments/assets/16cec9eb-383d-4b89-b7a8-d48fcfd5878e)
