### ISSUE TITLE
NRW ABC-Schutz vervollständigen

### ISSUE THREAD

**Issue by LaGGi97** [jonas-koeritz/Taktische-Zeichen#160]
Aus den Konzepten des Landes NRW fehlen im Bereich ABC-Schutz noch folgende Zeichen:

- ABC-BEREITSCHAFT
- ABC-Z
- P-DEKON 10
- P-DEKON 30
- V-DEKON-Z 25
- V-DEKON-B 50

- G-Dekon (Geräte-Dekontaminationsplatz)
- ANALYTISCHE TASK FORCE
- MESS-Z (ÜM 1) (Überörtliche Hilfe „Messen“ – Stufe 1)
- MESS-Z (ÜM 2) (Überörtliche Hilfe „Messen“ – Stufe 2)

- DEKON-LKW P (auch GW Dekon P)   Dekontaminationslastkraftwagen Personen
- AB-V-DEKON (Abrollbehälter Dekontamination-Verletzte)
- ABCErkKW (n ABC-Erkundungskraftwagen)
- MTW/MTW (in orange)
- ABC Messtrupp (wie Messfahrzeug nur als Trupp)
- Dekontaminationsplatz

[Katastrophenschutz NRW: ABC-Schutz](https://www.idf.nrw.de/service/downloads/pdf/interschutz_2015/medien_interschutz_poster_4_abc_schutz.pdf)

**Comment by jonas-koeritz** [comment]
Gibts eine Erklärung zu dem Kreis um das "Dekon" Symbol auf einigen aber nicht allen Zeichen? Den würde Ich sonst weglassen...

**Comment by LaGGi97** [comment]
Ich denke hier ist gemeint, dass diese Einheiten einen Dekontaminationaplatz (Platz =Kreis) aufbauen können.
Siehe  Seite 23 - 25
https://lernkompass.idf.nrw/goto.php?target=file_336_download&client_id=Feuer

**Comment by jonas-koeritz** [comment]
Ergibt Sinn, machen nur die Feuerwehren scheinbar meistens nicht so. Dann nehme Ich den Kreis zumindest für die spezifischen Symbole mit "Durchsatzangabe" mal auf.
