### ISSUE TITLE
Doppeltes Zeichen: Stab & BR-Stab

### ISSUE THREAD

**Issue by Daugl** [jonas-koeritz/Taktische-Zeichen#163]
Die Zeichen "Stab" und "BR-Stab" sind bis auf den Titel identisch. EIne Unterscheidung macht meiner Meinung nach hier keinen Sinn.

**Comment by jonas-koeritz** [comment]
Gibt es für den BR-Stab eine alternative Darstellung? Ansonsten werde Ich das einfach entfernen.
