### ISSUE TITLE
Technischer Berater

### ISSUE THREAD

**Issue by NikkiSiTa** [jonas-koeritz/Taktische-Zeichen#165]
Nach aktuell in den THW Unterlagen zu findenden taktischen Zeichen, werden Technische Berater (Bau, Hochwasserschutz und Naturgefahren, Sprengen,...) mit dem allgemeinen Symbol "TeBe" in der Person abgebildet und dann links unten die Art (Bau, HuN,...) angegeben und rechts unten die Organisation. 
Grundlage sind die neuen Sätze taktischer Zeichen im THW E-Learning Portal (nicht öffentlich zugänglich).

Der Request hier bezieht sich auf ein allgemeines TeBe Symbol.
Ausprägungen TeBe Bau, TeBe HuN und TeBe Sprengen wären dann darauf entstehende Folge-Issues.

![TeBe_Bau](https://user-images.githubusercontent.com/100095444/232791452-4bdc3613-68aa-487c-bc25-7a7eb92274e1.png)

**Comment by Resortler** [comment]
![Technischer_Berater_Ortung](https://user-images.githubusercontent.com/131306841/233831290-63a834bf-fae7-4433-a289-d923acaef478.svg)
![Technischer_Berater_Bau](https://user-images.githubusercontent.com/131306841/233831291-fcb631fd-c651-4a60-8090-f8e67979054c.svg)

Ich habe den TeBe Bau und Ortung erstellt. Sie müssen nur noch in die Sammlung übernommen werden.
