### ISSUE TITLE
Darstellung in invertierter Form

### ISSUE THREAD

**Issue by Resortler** [jonas-koeritz/Taktische-Zeichen#167]
Die Darstellung der Zeichen in invertierter Form verschafft ein einheitliches Bild, wenn die Lagekarte von Hand um Zeichen ergänzt wird und sie sind aus etwas Entfernung, z.B. der offenen MTW-Tür aus, besser erkennbar.
Evtl. kann dadurch auch die schwarze Konturkante entfallen, wenn als Referenz die im THW Extranet verfügbaren Zeichen genommen werden.

Beispiel Anhänger:
![Anhänger](https://user-images.githubusercontent.com/131306841/233831663-0671a530-a33f-474f-a5b7-17086f84a5a9.svg)
![Anhänger_invertiert](https://user-images.githubusercontent.com/131306841/233831661-756d9645-765f-4240-b43a-56b106f6ea91.svg)

Bergungsgruppe invertiert, ohne schwarze Konturkante.
![Bergungsgruppe](https://user-images.githubusercontent.com/131306841/233831961-ff82ee11-1451-4d92-9462-85827cd1a350.svg)
![Bergungsgruppe_invertiert_ohne_Kontur](https://user-images.githubusercontent.com/131306841/233831964-4f7019ba-96b9-46b5-b916-09096fa98b6a.svg)

**Comment by jonas-koeritz** [comment]
Finally: Fixed(?), siehe aktuelles pre-release
