### ISSUE TITLE
BÖ

### ISSUE THREAD

**Issue by wsaal** [jonas-koeritz/Taktische-Zeichen#171]
THW-Person BÖH ist alte Bezeichnung. Jetzt: BÖ
https://thwiki.org/t=Beauftragter_f%C3%BCr_%C3%96ffentlichkeitsarbeit

**Comment by jonas-koeritz** [comment]
Erledigt

**Comment by jonas-koeritz** [comment]
Da habe Ich keine Macht drüber. Das Projekt wird nicht von mir betreut. Ansprechpartner ist da am ehesten Tristan (https://gitlab.com/tristanlins).
