### ISSUE TITLE
ILS

### ISSUE THREAD

**Issue by hyperjojo** [jonas-koeritz/Taktische-Zeichen#173]
Um nicht nur Leitstellen im allgemeinen, sondern die Integrierten Leitstellen (ILS) Feuerwehr und Rettungsdienst gezielt darzustellen, wäre ein Symbol für die ILS hilfreich:
![image](https://github.com/jonas-koeritz/Taktische-Zeichen/assets/141624587/c1d093a6-e367-4def-804b-ed94ed9db7ba)

Vielen Dank!

**Comment by pcfreak1201** [comment]
Moin!
Wobei das in NRW eigentlich der Standard ist und nur mit LS gekennzeichnet wird. Hängt also von der Betrachtungsseite ab.
Aber haben ist besser als brauchen ;-)
