### ISSUE TITLE
Schadenskonto / Schadensstellen fehlender Title & Größe

### ISSUE THREAD

**Issue by Falke-Design** [jonas-koeritz/Taktische-Zeichen#174]
Beim einbinden der Zeichen in meine Software www.lagekarte.info funktionieren alle Zeichen super, nur die Schadens-Zeichen machen mir ein paar kleine Probleme und diese wollte ich rückmelden.

1. Bei allen Schadenskonto / Schadensstellen fehlt das Title Attribute.
2. Das Verhältnis zu den anderen Zeichen stimmt aus meiner Sicht nicht. Die Schadens-Zeichen sind viel zu groß:
![grafik](https://github.com/user-attachments/assets/fbae6e4d-decd-4ec4-a170-c9a9f1157e6c)
3. Und das `viewbox` Attribute ist falsch geschrieben, es sollte `viewBox` sein.

Glückwunsch noch zur gelungen Sammlung an Zeichen. Ich habe selber bereits viele Zeichen erstellt und weiß wie viel Arbeit das ist ... 
Viele User von mir haben sich auch schon eine Einbindung deiner Zeichen in meiner Software gewünscht, daher kann ich auch hier nur positives Feedback weiterleiten.

**Comment by jonas-koeritz** [comment]
Die "title" Attribute habe Ich hinzugefügt. Gleichzeitig auch mal ein "S" bei den Schadensstellen ergänzt (steht spannenderweise in beiden Varianten nicht im Duden, aber zwei "S" scheint gebräuchlicher/korrekter zu sein). Das viewBox Attribut ist jetzt konsistent mit dem SVG-Standard "viewBox" geschrieben.
Das Verhältnis der Schadenskonten/Schadensstellen zum Rest ist für die Schadenskonten so gewollt (die liegen ja meistens außerhalb der Karte und sind dann tatsächlich relativ groß, so zumindest auf unseren Magnetvorlagen beim THW). Die Schadensstellen sind wirklich etwas überdimensioniert, dafür kann man SVGs ja aber schön skalieren, Ich experimentiere da aber nochmal mit.
