### ISSUE TITLE
fehlerhafte Zentrierung im Firefox

### ISSUE THREAD

**Issue by MartinBoehmer** [jonas-koeritz/Taktische-Zeichen#2]
Bei Verwendung der SVGs im Firefox (mit draw.io) ist die Schrift vertikal nicht korrekt zentriert (vgl. Screenshot).
![el-exzentrisch](https://cloud.githubusercontent.com/assets/26457438/24037375/e27b1848-0afd-11e7-8335-45cf6704a40b.PNG)

Das Problem kann laut [dem Kommentar auf dieser Webseite](https://coderwall.com/p/a9nkrw/center-text-in-svg-rect-horz-and-vert) durch Verwendung des Attributs `dominant-baseline` statt `alignment-baseline` behoben werden.

Ich habe das ausprobiert und kann die Lösung bestätigen (Firefox 47.0.1) Daher schlage ich die Änderung des Attributs vor.

**Comment by MartinBoehmer** [comment]
Hm, ich sehe gerade, dass die exzentrische Darstellung der Darstellung der [Emp­feh­lun­gen für Tak­ti­sche Zei­chen im Be­völ­ke­rungs­schutz des BBK](http://www.bbk.bund.de/SharedDocs/Downloads/BBK/DE/FIS/DownloadsRechtundVorschriften/Volltext_Fw_Dv/SKK_DV_102_2012.html) entspricht.

Letztendlich ist mir egal, wie die Schrift ausgerichtet ist. Der Issue ist aber weiter gültig, da die Ausrichtung der SVGs im Firefox und den bereitgestellten PNGs & JPEG inkonsistent ist.

**Comment by jonas-koeritz** [comment]
Die Schrift ist jetzt mittig, wo genau ist denn die Ausrichtung der Schrift definiert? Beim überfliegen des Dokumentes konnte Ich leider nichts finden.

**Comment by MartinBoehmer** [comment]
Sie ist nicht definiert, daher ist es m.E. auch egal.
Allerdings zeigen die Beispiele auf Seite 40 die exzentrische, vertikale Ausrichtung.
