### ISSUE TITLE
Ergänzung von Zeichen für Hilfsorganisationen

### ISSUE THREAD

**Issue by MartinBoehmer** [jonas-koeritz/Taktische-Zeichen#3]
Die Auswahl der taktischen Zeichen deckt derzeit nicht die Anforderungen von Hilfsorganisationen (DRK, MHD, JUH, ASB) ab. Daher anbei eine Liste von wünschenswerten Ergänzungen.

Die Referenz-Nummern in der Liste beziehen sich auf die Nummerierung der [Emp­feh­lun­gen für Tak­ti­sche Zei­chen im Be­völ­ke­rungs­schutz](http://www.bbk.bund.de/SharedDocs/Downloads/BBK/DE/FIS/DownloadsRechtundVorschriften/Volltext_Fw_Dv/SKK_DV_102_2012.html). Generell sollten die taktischen Zeichen jedoch nicht auf eine konkrete Hilfsorganisation bezogen sein, wie bei einigen der referenzierten Beispiele. Ausnahme: Rotkreuzbeauftragter.

[Ergänzungen Taktische Zeichen.docx](https://github.com/jonas-koeritz/Taktische-Zeichen/files/850362/Erganzungen.Taktische.Zeichen.docx)

(PDF Version der Datei wird von GitHub nicht akzeptiert...)

**Comment by jonas-koeritz** [comment]
Ich habe die Symbole ergänzt, kannst du einen Blick drüber werfen ob die alle soweit okay sind?

**Comment by MartinBoehmer** [comment]
Das ging schnell. Spitze!

Hab noch nicht alle Zeichen durch. Hier der aktuelle Zwischenstand. Rest folgt die Tage.

Folgende Zeichen fehlen noch:
- Trupp Technik & Sicherheit
- Truppführer Technik & Sicherheit
- Truppführer Verpflegung (nicht im Word-Dokument aufgeführt)

Folgende Zeichen haben m.E. einen irreführenden Dateinamen:
- Einsatzeinheit - Sanitätsdienst.svg: Die Datei sollte nur `Einsatzeinheit.svg` heißen. Es handelt sich dabei um eine [standardisierte, taktische Formation](https://de.wikipedia.org/wiki/Einsatzeinheit_(Deutschland)), die vorwiegend durch HiOrgs besetzt wird.
- Zugführer Einsatzeinheit Rettungsdienst.svg: die Datei sollte nur `Zugführer Einsatzeinheit.svg` heißen. Eine Einsatzeinheit hat nicht direkt mit dem Rettungsdienst zu tun (vgl. Link oben), sie ist vielmehr eine mutlifunktionale Formation in der Gefahrenabwehr.

Betreuungstrupp: Das allgemeine Zeichen ist ok. Könntest du zusätzlich noch ein eigenes Zeichen für einen Trupp soziale Betreuung ergänzen? Das BBK Dokument zeigt unter 10.3.28 eine Gruppe (die brauchen wir nicht, da wir für Gruppenstärke das allgemeine Zeichen Betreuungsgruppe nehmen).

**Comment by jonas-koeritz** [comment]
Danke für die Rückmeldung und die Infos! Ich schaue da bei Gelegenheit
nochmal drüber. Die fehlenden Zeichen kann Ich gerne noch ergänzen. Ich
sollte mir langsam Gedanken darüber machen wie man die Zeichen etwas
Kategorisieren kann damit sie leichter zu finden sind.

Martin Böhmer <notifications@github.com> schrieb am Fr., 17. März 2017,
21:17:

**Comment by MartinBoehmer** [comment]
Ich habe einen Vorschlag zur Kategorisierung. Die muss ich ohnehin für die draw.io Bibliotheken machen. Den Vorschlag führe ich die Tage in einen eigenen Issue aus.

**Comment by MartinBoehmer** [comment]
Kannst du abschätzen, wann du diesen Issue schließen kannst? Es besteht keine dringende Eile meinerseits. Ich muss nur wissen, für wann ich die taktischen Zeichen bei uns intern ankündigen kann.

**Comment by jonas-koeritz** [comment]
Ich arbeite gerade an der Kategorisierung. Danach wollte Ich die noch fehlenden Zeichen dann gleich in das neue System übernehmen. Eventuell wird es heute noch was.

**Comment by jonas-koeritz** [comment]
Wie sehen diese Zeichen denn aus?

- Truppführer Technik & Sicherheit
- Truppführer Verpflegung (nicht im Word-Dokument aufgeführt)

**Comment by MartinBoehmer** [comment]
In erstem Fall das Standard-TF-Zeichen um den "Maulschlüssel" und den Schriftzug "TS" darüber ergänzen. Ein Beispiel zeigt das BBK-Dokument unter 10.3.18 als TS-Gruppe.

Im zweiten Fall den "Pacman" in das Standard-TF-Zeichen setzen. Der Pacman ist im BBK-Dokument unter 6.4.7 zu finden.

**Comment by jonas-koeritz** [comment]
Okay, Ich erstelle die Zeichen im Laufe des Tages.

**Comment by MartinBoehmer** [comment]
Welcher Tag genau? :-)

**Comment by jonas-koeritz** [comment]
Ich schaue mir das morgen (Montag) an und werde sicher auch fertig ;)

Martin Böhmer <notifications@github.com> schrieb am So., 2. Apr. 2017,
11:54:

**Comment by jonas-koeritz** [comment]
Erledigt:

- [Truppführer Technik und Sicherheit](https://github.com/jonas-koeritz/Taktische-Zeichen/blob/master/symbols/Rettungswesen%20Personen/Truppf%C3%BChrer%20Technik%20und%20Sicherheit.svg)
- [Truppführer Verpflegung](https://github.com/jonas-koeritz/Taktische-Zeichen/blob/master/symbols/Rettungswesen%20Personen/Truppf%C3%BChrer%20Verpflegung.svg)

**Comment by MartinBoehmer** [comment]
Super, danke.

Noch eine Klugscheißer-Anmerkung: Bei einigen Dateien hast du dich vertippt:
Fahrzeuge/Anhäger
Fahrzeuge/Container, Abbrollbehälter
Rettungswesen Einrichtungen/Sammelplatz für betroffene (Betroffene ist klein geschrieben)
Sonstiges/Geringfüggig erhöhte Aktivität

**Comment by jonas-koeritz** [comment]
Ja da war viel Handarbeit dabei ;) korrigiere ich morgen nochmal durch.

Martin Böhmer <notifications@github.com> schrieb am Mo., 3. Apr. 2017,
23:05:
