### ISSUE TITLE
grunt render-all erzeugt nur 1024x1024 png dateien 

### ISSUE THREAD

**Issue by Siedlerchr** [jonas-koeritz/Taktische-Zeichen#30]
Hi,

erstmal danke für die Icons ;) Kann ich super gebrauchen.
Ich habe gerade festgestellt, dass grunt render all nur die 1024x1024 png Dateien erzeugt,
Von allen anderen Größen werden zwar die Ordner erstellt, aber nicht die png Dateien. 

Irgendeine Idee warum die nicht erzeugt werden?

**Comment by jonas-koeritz** [comment]
Hallo, ist ImageMagick Installiert? Das Skript verwendet das Kommando magick um die kleineren Dateien durch verkleinern der 1024er Symbole zu erzeugen.

**Comment by Siedlerchr** [comment]
Ich habs gerade nochmal mnauell überprüft, jetzt wirft mir magick den error:
magick: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/509.
Sieht so aus als fehlen mir noch ein paar externe libs.

**Comment by jonas-koeritz** [comment]
Libpng eventuell ;)?

Christoph <notifications@github.com> schrieb am Mi., 6. Dez. 2017, 19:58:

**Comment by Siedlerchr** [comment]
Ja, erstaunlicherweise ist sie eigenltich installiert (sogar die dev) Aber er findet sie nicht beim builden von imagemagick. Ich werds morgen nochmal neu probieren.

**Comment by Siedlerchr** [comment]
Funktioniert auch mit älteren imagemagick versionen. Musste dafür nur statt magick  das Programm convert nutzen,
