### ISSUE TITLE
angeschlagen, teilzerstört, totalzerstört

### ISSUE THREAD

**Issue by KBreker** [jonas-koeritz/Taktische-Zeichen#36]
Mein Vorschlag - siehe Anhang ...
[Zerstörung_Beschädigung.zip](https://github.com/jonas-koeritz/Taktische-Zeichen/files/2409008/Zerstorung_Beschadigung.zip)

**Comment by jonas-koeritz** [comment]
Hallo,

Danke für die vielen Vorschläge, die schaue Ich mir morgen Mal genauer an. Die Symbole aus diesem Issue gibt es aber schon hier: https://github.com/jonas-koeritz/Taktische-Zeichen/tree/master/symbols/Schäden

**Comment by jonas-koeritz** [comment]
Bereits implementiert.
