### ISSUE TITLE
Add: ELRD ergänzen

### ISSUE THREAD

**Issue by ReneDens** [jonas-koeritz/Taktische-Zeichen#38]
Führungsperson des Rettungsdienstes mit Funktionsnamen ELRD ergänzen.

**Comment by ReneDens** [comment]
Wäre  

`{
					"name": "Einsatzleiter Rettungsdienst",
					"template": "Person.svg",
					"color_primary": "#FFFF00",
					"color_secondary": "#000000",
					"text_color": "#000000",
					"font_size": "230%",
					"unit": "ELRD",
					"variants": {
						"special_function": "Einsatzleiter Rettungsdienst"
					}
				},`

theoretisch die richtige Variante?

**Comment by jonas-koeritz** [comment]
Ja das sieht gut aus! Kann gerne als Pull-Request kommen ;)

**Comment by ReneDens** [comment]
Also das Git tut jetzt hier kann aufgrund fehlender Berechtigung nur kein publish branch und folglich kein Pull-Request machen. :-)
