### ISSUE TITLE
Kategorisierung der Zeichen

### ISSUE THREAD

**Issue by MartinBoehmer** [jonas-koeritz/Taktische-Zeichen#4]
Die Menge der Zeichen wächst und es wird unübersichtlich.

Für die Erstellung der draw.io Bibliotheken habe ich eine Kategorisierung vorgenommen, die sich an der Gliederung der [Emp­feh­lun­gen für Tak­ti­sche Zei­chen im Be­völ­ke­rungs­schutz](http://www.bbk.bund.de/SharedDocs/Downloads/BBK/DE/FIS/DownloadsRechtundVorschriften/Volltext_Fw_Dv/SKK_DV_102_2012.html) orientiert, insb. an den dort aufgeführten Beispielen.

Die Kategorisierung ist in [meiner Konfigurationsdatei](https://github.com/MartinBoehmer/Taktische-Zeichen-drawio/blob/master/tz-drawio.ini) zu finden und könnte hier als Ordnerstruktur dienen (Sektion = Ordner). Jede andere Kategorisierung ist aber ebenso willkommen.

**Comment by jonas-koeritz** [comment]
Die Zeichen werden jetzt automatisch in Kategorien eingeteilt.
