### ISSUE TITLE
Quervergleich der Symbole mit www.mobile-lagekarte.de

### ISSUE THREAD

**Issue by ReneDens** [jonas-koeritz/Taktische-Zeichen#41]
Quervergleich der vorhandenen und Ergänzen der noch nicht vorhandenen Symbole mit https://www.mobile-lagekarte.de/

**Comment by jonas-koeritz** [comment]
Gibt es hier noch neue Infos?

**Comment by jonas-koeritz** [comment]
Da Ich keinen Zugriff auf die Software oder eine Liste der Zeichen habe ist hier erstmal zu.
