### ISSUE TITLE
Schriftart wird nicht in SVG eingebettet

### ISSUE THREAD

**Issue by ReneDens** [jonas-koeritz/Taktische-Zeichen#44]
Die Schriftart Roboto Slab Bold in entsprechender Schriftgrösse ist nicht in den SVG Files eingebettet wodurch die Schrift in $Standardeinstellung des öffnenden Programms angezeigt wird (zB bei Inkscape sans-serif in 16pt).
Wäre es machbar, dass in jedes File entsprechend der Blob für die TTF reinkommt?

**Comment by jonas-koeritz** [comment]
Aktuell werden die Schriftarten als woff eingebettet. Auf TTF habe Ich bisher zugunsten der Dateigröße verzichtet (da die Dateien von mir nie in Inkscape bearbeitet werden). Ich plane allerdings das gesamte "Auto-Generieren" aus dem Projekt zu entfernen um die Pflege einzelner Zeichen und auch das erstellen von eigenen Zeichen zu vereinfachen. Meine "Normung" besteht dann nur noch aus den Grundregeln wie: Deckungsgleichheit, eingebettete Schrift (dann gerne auch woff und ttf oder nur ttf aus Kompatiblitätsgründen), zu verwendende Farben und Grundzeichen.

**Comment by ReneDens** [comment]
Ich hab da mittlerweile meinen quasi-Fork erstellt (aufgrund von technischer Unabhängigkeit nicht als echter Fork): https://github.com/ReneDens/Bibliothek-taktische-Zeichen

Ich habe da einiges erstellt und auch schnell per Script überall das TTF der Schriftart reingepfuscht.

Kannst du dir ja anschauen und wenn du magst miteinbauen.

**Comment by jonas-koeritz** [comment]
Hast du mal ein Beispiel dafür wo die TTF so eingebunden ist dass Inkscape was damit anfangen kann?

**Comment by ReneDens** [comment]
Hier mal n Beispiel.
Es bleibt zu beachten, dass ich meine Teile einfach ausm Export von Inkscape übernommen habe. Es kann also noch sein, dass Überflüssiges drin ist. 

> <style
       type="text/css"
       id="style2"><![CDATA[
			@font-face {
				font-family: 'Roboto Slab Bold';
    			src: url(data:application/font-woff;charset=utf-8;base64,HIER_FETTER_BASE64_BLOCK_SCHRIFTART==) format('woff');
			}
		]]></style>


[Einsatzleiter Rettungsdienst Text.zip](https://github.com/jonas-koeritz/Taktische-Zeichen/files/2737996/Einsatzleiter.Rettungsdienst.Text.zip)

**Comment by jonas-koeritz** [comment]
Genau so wie in deinem Kommentar werden aktuell die Schriften eingebettet. In allen Dateien in denen Text enthalten ist ist die Schriftart als "woff" eingebettet, sonst würde das Rendering garnicht funktionieren. Inkscape kümmert das nur wenig, ich habe es auch nicht hinbekommen eine Datei zu erzeugen in der Inkscape die Schrift anzeigt.

Ich schaue mir die angehängte Datei aber auch nochmal an.

**Comment by jonas-koeritz** [comment]
Habe den Fehler gefunden. Die Attribute `font-family`. `dominant-baseline` etc. werden zwar von WebKit und auch PhantomJS unterstützt, gehören aber nicht zum SVG Standard. Die Anwendung der Schriftart muss also im `style` Attribut erfolgen. Ich werde sämtliche Zeichen anpassen und entsprechend korrigieren. Danach zeigt auch Inkscape die Zeichen korrekt an.

**Comment by jonas-koeritz** [comment]
> Ich hab da mittlerweile meinen quasi-Fork erstellt (aufgrund von technischer Unabhängigkeit nicht als echter Fork): https://github.com/ReneDens/Bibliothek-taktische-Zeichen
> 
> Ich habe da einiges erstellt und auch schnell per Script überall das TTF der Schriftart reingepfuscht.
> 
> Kannst du dir ja anschauen und wenn du magst miteinbauen.

Wieso eigentlich "aufgrund von technischer Unabhängigkeit nicht als echter Fork"? Inwiefern ist ein Fork technisch abhängig?

**Comment by ReneDens** [comment]
> Habe den Fehler gefunden. Die Attribute `font-family`. `dominant-baseline` etc. werden zwar von WebKit und auch PhantomJS unterstützt, gehören aber nicht zum SVG Standard. Die Anwendung der Schriftart muss also im `style` Attribut erfolgen. Ich werde sämtliche Zeichen anpassen und entsprechend korrigieren. Danach zeigt auch Inkscape die Zeichen korrekt an.

Ah, sowas hatte ich schon vermutet, dass es nicht an der Einbettung der Schriftart liegt.
(Ich hatte im Übrigen teilweise Dateien bei denen sie nicht als woff drin war, da muss dann anscheinend bei meinem Clone irgendwas komisch geworden sein.

Naja, summa summarum ist der Fehler bei Inkscape bzw dem SVG-Standard-Definition gefunden. Freut mich :-)

**Comment by ReneDens** [comment]
> Wieso eigentlich "aufgrund von technischer Unabhängigkeit nicht als echter Fork"? Inwiefern ist ein Fork technisch abhängig?

Ah, da hab ich zu wenig Kontext geliefert. Da würde mir sonst meine drumrumgestrickte Git-Magie-Skript-Pfuscherei bei jedem deiner Release melden ob ich den nicht auch bei mir reinmergen will... Und das wollte ich vermeiden.
Du hast ja den Link zu meinem Repo, falls du irgendwelche Dinge findest, die du bei dir haben willst (zB das Symbol Bergrettung).

**Comment by ReneDens** [comment]
Zu meinen Fehlern kommt noch hinzu dass manchmal der Teil mit der Schriftart garnicht eingebettet wird, was zu meinem Fehlerbild führt:

Beispiel aus der Datei des Einsatzleiter Rettungsdienst:

> <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="256" height="256">
	<defs>
		<style type="text/css">
		{% include './fonts/fonts.j2' %}
		</style>
</svg>

**Comment by jonas-koeritz** [comment]
Das `{% include './fonts/fonts.j2' %}` sollte beim erstellen mit make ersetzt werden durch die Schriftart.
