### ISSUE TITLE
Beschriftung bei Fahrzeugen deplaziert

### ISSUE THREAD

**Issue by MartinBoehmer** [jonas-koeritz/Taktische-Zeichen#5]
Bei einigen Fahrzeugen mit Beschriftungen in der linken, oberen Ecke sind die Schriftzüge deplaziert. Das Problem besteht bereits in den Quelldateien. Betroffen sind:
- RTW
- KTW
- NAW
- NEF

![fz-schrift](https://cloud.githubusercontent.com/assets/26457438/24111963/643ad9d0-0d98-11e7-91af-84301e812eee.PNG)

**Comment by MartinBoehmer** [comment]
Seltsam, die Korrektur hat das Problem bei mir leider nicht behoben. Habe den y-Wert des Textes auf 110 gesetzt, dann war es ok. 110 ist geraten und ausprobiert, nicht berechnet...

![fz-schrift2](https://cloud.githubusercontent.com/assets/26457438/24117120/39bd7ea4-0da9-11e7-90d5-b72c5442267f.PNG)

**Comment by jonas-koeritz** [comment]
Hatte es nicht getestet, ich schaue es mir morgen nochmal an.

Martin Böhmer <notifications@github.com> schrieb am Mo., 20. März 2017,
20:11:

**Comment by MartinBoehmer** [comment]
Passt, danke!
