### ISSUE TITLE
Seitenverhältnis Fm-Zeichen

### ISSUE THREAD

**Issue by C0FFEEC0FFEE** [jonas-koeritz/Taktische-Zeichen#52]
Beim THW werden die Taktischen Zeichen auf Papier gedruckt, einlaminiert und mit sog. [C-Profilen](https://www.magna-c.de/Magnetfolien-und-baender-Magnetische-Lagerkennzeichnung/Magnetische-Kennzeichnung/Magnetische-C-Profil-Rollen.html) auf die Lagekarten aufgebracht. Diese Profile haben die folgendem Maße (innen):
S1: 90x48 mm
S2, S4: 45x48 mm
S6 (Fm): 90x23 mm

Das Seitenverhältnis der [Fm Zeichen](https://github.com/jonas-koeritz/Taktische-Zeichen/tree/master/symbols/Funk) (1:3,625) stimmt nicht mit dem der dienstlich gelieferten Zeichen (1:4,34) überein. Ich habe mal ein Beispiel der dienstlich gelieferten Zeichen (svg) angehängt. Ich könnte den Rest der Fm-Zeichen (Fernsprechen, Telefax, E-Mail, ...) ergänzen, stellt sich nur die Frage ob unser Seitenverhältnis für Euch auch passt?

[S6-Zeichen_A4_leer.svg.zip](https://github.com/jonas-koeritz/Taktische-Zeichen/files/2746899/S6-Zeichen_A4_leer.svg.zip)

**Comment by jonas-koeritz** [comment]
Ich kann gerne die Fm Zeichen ergänzen, das Seitenverhältnis der SVG Datei ist hier immer 1:1 bei 256x256 Einheiten Größe. Falls du unterstützen möchtest: Beim Aufbau der zusätzlichen Zeichen am besten an den bereits vorhandenen orientieren.

Um in C-Profile eingepasst zu werden muss die Grafik ja nur zugeschnitten werden, sollte das nicht einfach passen überlege Ich mir noch etwas, für diese Problematik hatte Ich Mal angedacht irgendwie in den Dateien zu hinterlegen wie diese "gestreckt" werden können.

**Comment by jonas-koeritz** [comment]
Das "generieren" von fertigen PDF Dateien zum Ausdrucken für die Magnetprofile steht auch noch auf dem Plan 😉.

**Comment by C0FFEEC0FFEE** [comment]
Nur fürs Verständnis: Wenn die Dateien mit einem anderen Seitenverhältnis abgelegt werden als Sie gedruckt werden verzerrt es doch beim Druck die Schrift in dem Zeichen ggf. bis zur Unlesbarkeit, oder nicht? Beispiel: [S6-Zeichen_A4_fernsprechen.svg.zip](https://github.com/jonas-koeritz/Taktische-Zeichen/files/2748271/S6-Zeichen_A4_fernsprechen.svg.zip)

**Comment by jonas-koeritz** [comment]
Die Fernmeldezeichen für "DMO-Betrieb" und "TMO-Betrieb" lassen sich jetzt beliebig in der Breite verändern. Dadurch haben Sie allerdings Ihren transparenten Hintergrund verloren.

**Comment by C0FFEEC0FFEE** [comment]
Perfekt, Danke. :)

Wir nutzen die Fm-Zeichen klassisch mit weißem Hintergrund und verändern bei Fm-Verbindungen die Vordergrundfarbe des Zeichens (schwarz, rot, grün, blau, gelb). Ist es möglich die Vordergrundfarbe als Parameter zu definieren bzw. von allen relevanten Zeichen einen kompletten Satz in allen Farben zu erzeugen?

**Comment by C0FFEEC0FFEE** [comment]
Genau genommen ändert sich nur bei einem Teil die Vordergrundfarbe, nämlich beim Pfeil für die Richtungsanzeige, Beispiel: [S6-Zeichen_A4_sprechfunk01.svg.zip](https://github.com/jonas-koeritz/Taktische-Zeichen/files/2751710/S6-Zeichen_A4_sprechfunk01.svg.zip)

**Comment by C0FFEEC0FFEE** [comment]
Der Pfeil gibt an ob die Verbindung zur übergeordneten oder zur nachgeordneten Führungsebene besteht. Details sind in folgendem Dokument erläutert: [s6-übersicht Erläuterungen.pdf](https://github.com/jonas-koeritz/Taktische-Zeichen/files/2752254/s6-ubersicht.Erlauterungen.pdf). So sieht das ganze dann aus:
<img width="822" alt="bildschirmfoto 2019-01-12 um 17 40 52" src="https://user-images.githubusercontent.com/20687034/51075832-41b59900-1691-11e9-9e50-b20e1cdedb7f.png">

**Comment by jonas-koeritz** [comment]
Und welche Bedingungen haben die Farben?

**Comment by C0FFEEC0FFEE** [comment]
Die Farben haben keine feste Bedeutung, die kann der S6 je nach Lage selbst festlegen.

**Comment by jonas-koeritz** [comment]
Dann würde Ich eher in einer ausgedruckten Variante Platz für einen handschriftlichen Pfeil lassen statt fest Zeichen für diese Fälle zu erstellen.

**Comment by C0FFEEC0FFEE** [comment]
Zum Zeichnen der Pfeile von Hand ist in den Phasen des Einsatzes in welchen diese Zeichen vorwiegend genutzt werden (Änderung der Führungsorganisation) keine Zeit.

**Comment by dmth** [comment]
Statt die kompletten Pfeile Aufwärts/Abwärts farbig zu erzeugen, oder diese von Hand zu malen, wäre ggfs eine Zwischenlösung denkbar.

Der Pfeil ist Schwarz, aber der Bauch des Pfeiles ist nicht ausgefüllt und kann dann mit einem Fineliner in gewünschter Farbe gefüllt werden. Am längsten dauert eh das Beschreiben von Hand, ein Farbpunkt ist dann schnell gemacht (oder nachträglich eingebracht).

Beispiel: 
[PfeilAufAb.zip](https://github.com/jonas-koeritz/Taktische-Zeichen/files/3773452/PfeilAufAb.zip)

**Comment by jonas-koeritz** [comment]
Ursprüngliches Thema ist gelöst. Die Richtungspfeile in diversen Farben sind vermutlich als getrenntes Zeichen einfacher zu erstellen. Für die Verwendung am Whiteboard dann auch einfacher geeignet wenn diese einzeln ausgetauscht werden können.
