### ISSUE TITLE
Erweiterung der Gefahrenzeichen

### ISSUE THREAD

**Issue by THW-Hamm** [jonas-koeritz/Taktische-Zeichen#6]
Hallo jonas
Wäre es möglich das du die Gefahrenzeichen um Luftmangel, Gas, Elektrische Energie sowie den Verbandsplatz erweiterst ??

M.f.G. Thomas Panczak
THW Hamm
(Tomp@nexgo.de)

**Comment by jonas-koeritz** [comment]
Die Zeichen kann Ich gerne ergänzen. Der Verbandsplatz ist unter der aktuellen Bezeichnung Behandlungsplatz [schon dabei](https://github.com/jonas-koeritz/Taktische-Zeichen/blob/master/symbols/Einrichtungen/Behandlungsplatz.svg).

**Comment by THW-Hamm** [comment]
Hallo Jonas,

hatte noch eine alte Ausgabe mit Verbandplatzbezeichnung ;-(

Mir fehlt auch noch eine Verschüttet / verletzte Person

Außerdem habe ich das Problem das wenn ich die Symbole auf ca. 5mm für eine Exceltabelle verkleiner das mir die Strichstärke für die Personen zu dünn werden, hast Du dafür einen Abhilfe.

Gruß aus Hamm


----- Original Nachricht ----
Von:     Jonas Köritz <notifications@github.com>
An:      jonas-koeritz/Taktische-Zeichen <Taktische-Zeichen@noreply.github.com>
Datum:   25.05.2017 09:30
Betreff: Re: [jonas-koeritz/Taktische-Zeichen] Erweiterung der Gefahrenzeichen
 (#6)

**Comment by jonas-koeritz** [comment]
Gibt es bestimmte Zeichen bei denen das Problem besonders störend/auffällig ist?

**Comment by THW-Hamm** [comment]
Hallo Jonas,
sorry das ich mich jetzt erst melde. War für mehrere Wochen für ein Projekt unterwegs.

Das Problem tritt bei allen Personen bei den "Quadrate auf der Ecke" auf .
Der Waagerechte Strich vom der Verschütteten ist beim selben Symbol allerdings i.o. ,dort fälle es besonders auf.

 Im Anhang : ( oben bei den Personen auf der Schadensmeldung )

[Schadensmeldung.pdf](https://github.com/jonas-koeritz/Taktische-Zeichen/files/1082112/Schadensmeldung.pdf)

Gruß Thomas

**Comment by jonas-koeritz** [comment]
Endlich bin Ich dazu gekommen die Zeichen hinzuzufügen und deinen gemeldeten Fehler (hoffentlich) zu korrigieren.

**Comment by THW-Hamm** [comment]
Danke dir dafür . Werde es mal Testen.

Gruß Thomas


----- Original Nachricht ----
Von:     Jonas Köritz <notifications@github.com>
An:      jonas-koeritz/Taktische-Zeichen <Taktische-Zeichen@noreply.github.com>
Datum:   19.07.2017 09:46
Betreff: Re: [jonas-koeritz/Taktische-Zeichen] Erweiterung der Gefahrenzeichen
 (#6)
