### ISSUE TITLE
kommunale Fahrzeuge (Grundfarbe orange)

### ISSUE THREAD

**Issue by KBreker** [jonas-koeritz/Taktische-Zeichen#64]
Ahoi!

Die Erweiterung auf kommunale Fahrzeuge wäre auch noch hilfreich. Mir fallen konkret ein:

- LKW (geländegängig und nicht geländegängig)
- LKW-Ladekran geländegängig
- Anhänger
- Abrollbehälter
- Mehrzweckarbeitsboot
- PKW (geländegängig und nicht geländegängig)
- PKW-Anhänger
- MTW
- Kettenfahrzeug mit Beschriftung "Hägglunds" oder "Hägg"

**Comment by jonas-koeritz** [comment]
Welches Orange wäre da denn angebracht? Gibt's da eine Norm?

**Comment by KBreker** [comment]
Ahoi!

RAL 2011 wäre da sicher die korrekte Farbe: https://de.wikipedia.org/wiki/RAL-Farbe
