### ISSUE TITLE
Feuerwehr: ELW2

### ISSUE THREAD

**Issue by CloudMaker97** [jonas-koeritz/Taktische-Zeichen#66]
Das existierende Zeichen für die Feuerwehr "ELW1" als Einheit kann mit der selben Beschriftung mit ELW2 für die IuK-Einheiten adaptiert werden.

[URL zu einem Beispiel](https://i.imgur.com/o2NOfi8.png)

**Comment by dennis-heinrich** [comment]
Vielen Dank nochmal nachträglich!
Das Zeichen kam schon zwei mal zum Einsatz an der Einsatzstelle. 👍
