### ISSUE TITLE
Arztbesetzte Sanitätseinheiten

### ISSUE THREAD

**Issue by DerMudder** [jonas-koeritz/Taktische-Zeichen#67]
Es gibt noch die arztbesetzten Sanitätszüge / Gruppen sowie den Einsatzzug Nds 2017, welcher eine Kombination aus arztbesetzem Sanität und Betreuung ist.

**Comment by DieNrSieben** [comment]
@DerMudder Kannst du bewerten ob das Zeichen Rettungswesen_Einheiten/Einsatzeinheit das gleich ist wie vom Einsatzzug Niedersachsen?

**Comment by jonas-koeritz** [comment]
Gibt's hier schon einen "Beschluss"? Sonst mache ich das Issue bald mal zu.

**Comment by jonas-koeritz** [comment]
Gerne wieder öffnen wenn es eine einheitliche Regelung gibt, oder zumindest einen Konsens wie das aussehen soll ;)
