### ISSUE TITLE
Die Datei "COPYRIGHT.md" fehlt im Repo

### ISSUE THREAD

**Issue by dmth** [jonas-koeritz/Taktische-Zeichen#69]
Im Abschnitt "Lizenz" der Readme wird auf eine Datei "COPYRIGHT.md" verwiesen. Diese ist nicht teil des Repos.

**Comment by jonas-koeritz** [comment]
Das muss Ich dann wohl mal nachpflegen ;) rumliegen hab Ich die...ist wohl nicht mit ins git übernommen.

**Comment by jonas-koeritz** [comment]
Hast du vor eine Variante oder ein abgeleitetes Projekt zu erstellen? Dann trage dich gerne auch in die Liste in der README ein.

**Comment by dmth** [comment]
Nein, derzeit nicht. Vielleicht irgendwann (tm) mal einen Generator damit man direkt Druckvorlagen für C-Profile schaffen kann.
