### ISSUE TITLE
Mehr Blanko Zeichen

### ISSUE THREAD

**Issue by tristanlins** [jonas-koeritz/Taktische-Zeichen#79]
Mir fehlen ein paar Blanko Zeichen (ich benutze Blanko Zeichen gerne als Reserve).

- Taktische Einheit (einfacher rechteckiger Kasten)
- Trupp
- (Staffel)
- Gruppe
- Zug

Evtl. als Ergänzung zu den bereits vorhandenen (Führungstrupp, -staffel, -gruppe):

- Führungseinheit (rechteckiger Kasten mit Balken oben)
- Logistikeinheit (rechteckiger Kasten mit Balken unten)
- [ Logistiktrupp (Balken unten) ] - den gibt es zumindest beim THW glaube ich nicht, da ist das der Log-Fü-Trupp?! 
- Logistikgruppe (Balken unten)
- Logistikzug (Balken unten)

PS: ich hätte die Blanko Zeichen jetzt zusammen gefasst, kann dir aber auf Wunsch für jedes auch einen einzelnen Vorgang machen?!

**Comment by jonas-koeritz** [comment]
Passt so. Die fehlen mir auch noch.
