### ISSUE TITLE
Beschriftung von THW Zeichen oft zu lang

### ISSUE THREAD

**Issue by tristanlins** [jonas-koeritz/Taktische-Zeichen#80]
Bei einigen THW Fahrzeugen ist die Bezeichnung so lang, dass die Schrift aus dem taktischen Symbol raus läuft und damit abgeschnitten wirkt - weiß auf weiß ist nicht so gut zu lesen ;-)

Betroffen sind:

alle THW Personen, bei Personen ist die Schrift imo einfach grundsätzlich zu groß, nur hat das THW auch noch so lange Bezeichner :-|

![Screenshot_20200216_075710](https://user-images.githubusercontent.com/343404/74600439-09516d00-5092-11ea-8d33-b7288d46b608.png)

diese THW Fahrzeuge:

- NEA 2000 kVa
- NEA 50 kVA LiMa
- NEA 650 kVA
- SwPu 5.000l/min
- SwPu 15.000l/min
- SwPu 25.000l/min
- FüKomKW
- LKW-K 9 t
- LKW-K Lkr
- LKW-K Lkr 1,5t
- LKW-Lbw 
- LKW-Lbw 7 t
- Stapler 2 t
- Stapler 3 t

![Screenshot_20200216_075320](https://user-images.githubusercontent.com/343404/74600472-8bda2c80-5092-11ea-830f-6166e5db5e89.png)

**Comment by jonas-koeritz** [comment]
@hochwasser sind das Auswirkungen von #77?

**Comment by tristanlins** [comment]
Da ich die Generierung aber bisher noch nie lokal ausprobiert habe, kann ich das leider nicht beurteilen. Ich finde aber generell, dass die Schrift bei den meisten taktischen Zeichen sehr opulent ist. 🤔

**Comment by hochwasser** [comment]
@jonas-koeritz das ist nicht so einfach mit einem "Ja" zu beantworten.
Manche bezeichner sind recht lange und ich habe in den Templates (die ".j2t" Dateien, Beispiel "Helfer.j2t") ein "size" Attribut eingefügt:
```
{% if size is not defined %}
{% set size=300 %}
{% endif %}
<text x="128" y="128" style="font-family: 'Roboto Slab'; font-weight: bold; dominant-baseline: central; text-anchor: middle; font-size: {{size}}%;" fill="#FFFFFF">{{ fgr }}</text>
{% endif %}
```
Wir die Größe nicht angegeben, dann wird "300%" genommen.
Bei meinem Generieren ist die Schrift nicht über den Hintergrund hinaus gegangen, sonst hätte ich das angepasst. Vllt wäre eine absolute Angabe der Größe (pt, mm, px) besser geeignet eine konsistente Ausgabe zu erzeugen.

@jonas-koeritz & @tristanlins was für Versionen benutzt ihr zum Generieren bzw Anschauen der Dateien?

**Comment by jonas-koeritz** [comment]
Ich habe angefangen die größen zu korrigieren.
Zum anschauen der Dateien verwende Ich grundsätzlich Chromium, die Generierung erfolgt in phantomjs (Version 2.1.1).
Ausschlaggebend ist für mich die Darstellung in Chrome/Chromium, in dieser sind die Texte zu groß wie auf den Bildern oben zu sehen.

**Comment by hochwasser** [comment]
Kann ich dir helfen?

Ich hatte überlegt, die Größe in eine extra Datei zu packen und allgemein kleiner zu machen um weniger Anpassungen vornehmen zu müßen.
In der einzelnen Grafik die Größe nur noch zu ändern wenn diese zu groß ist.

**Comment by hochwasser** [comment]
Ich habe gestern noch etwas experimentiert:
```
{% if size is not defined %}
    {% if fgr|length > 3 %}
        {% set size=200 %}
    {% elif fgr|length > 2 %}
        {% set size=250 %}
    {% else %}
        {% set size=280 %}
    {% endif %}
{% endif %}
```
Das ist eine Variante für die Personentemplates. Je nach Länge der Zeichenkette wird die Größe angepasst. Eine automatische Variante, bei der die Zeichengröße an eine Box angepasst wird, habe ich nicht gefunden. Das wäre eine Lösung bei der nicht für jede Grafik die Zeichengröße angepasst werden muss.

Die Größen müssen noch an Chrome angepasst werden. Es gibt auch einen unterschied in der Darstellung zwischen Linux und Windows bei mir.

**Comment by tristanlins** [comment]
> @tristanlins was für Versionen benutzt ihr zum Generieren bzw Anschauen der Dateien?

Ich verwende Chrome unter KDE neon Linux.
Und eigentlich auch nur meinen Generator, aus dem ich die Screenshots oben erstellt habe ;-)
Bisher war ich noch nicht dazu gekommen, mich mal mit der Generierung auseinander zu setzen, da mir momentan auch noch die Tools dafür fehlen (ich weiß, sollte kein Akt sein die zu installieren, habe ich mich aber noch nicht mit beschäftigt).

**Comment by jonas-koeritz** [comment]
Aktuell in allen Zeichen soweit Ich das geprüft habe korrigiert.
