### ISSUE TITLE
Veraltete und redundante THW-Einheiten

### ISSUE THREAD

**Issue by Maximilian-Beyer** [jonas-koeritz/Taktische-Zeichen#82]
Mir ist aufgefallen, dass die ganzen durch das Neukonzept veralteten Einheiten wie Beleuchtung oder 2. Bergungsgruppe noch enthalten sind.

Falls die Grundsatzentscheidung fällt, diese beizubehalten, wäre es der Übersichtlichkeit mMn dienlich, diese Zeichen im Dateinamen mit einen entsprechenden Präfix zu versehen.

Darüber hinaus gibt es redundante Symbole z.B. "Schwere Bergungsgruppe", denn es gibt ja auch noch gemäß der aktuellen StAN die Symbole "FGr_SB_A" und "FGr_SB_B". Oder soll es generell auch ein Einheitensymbol ohne Typ geben? Dann fehlen aber einige, insbesondere die FGr W, von der es nach aktueller StAN nur noch einen Typ gibt.

**Comment by jonas-koeritz** [comment]
Grundsätzlich bleibe Ich dabei alle Zeichen beizubehalten. Hintergrund ist unter anderem die Darstellung von "historischen Lagen". Nur weil das Neukonzept eingeführt ist ändert sich nicht was z.B. vor 2 Jahren im Einsatz passiert ist, um diese Lagen darstellen zu können benötigt man auch die vorherigen Zeichen.

Eine Markierung der entsprechenden Zeichen ist in Planung, hierzu wird aber nicht der Dateiname sondern ein Metadatenfeld Verwendung finden, zusätzlich werden die "veralteten" Zeichen dann auch in ein eigenes Verzeichnis verschoben um die Übersichtlichkeit zu erhöhen.

Zu den redundanten/fehlenden Symbolen: Wenn die Untertypen fehlen dann sind das fehlende Zeichen. Wenn die Darstellung ohne Typ fehlt dann ist dies ebenfalls ein fehlendes Zeichen und kann nachgereicht oder von mir erstellt werden. Ich möchte eine möglichst vollständige Auswahl an Zeichen bieten bei der kein "normaler Anwender" nachträglich irgendwelche Zeichen verändern muss um alle Symbole zu bekommen die er benötigt.

**Comment by jonas-koeritz** [comment]
Korrigiert, war eine Auswirkung der "unnötigen" Verwendung von Templates in den Zeichen.
