### ISSUE TITLE
Neue THW StAN 2020

### ISSUE THREAD

**Issue by dmth** [jonas-koeritz/Taktische-Zeichen#84]
Hi,

die neue StAN des THW ist veröffentlicht. Aus der Fachgruppe Logistik wird der Fachzug Logistik.

D.h. es gibt nun:
- Fachzug Logistik
- ZTr Log (Zugtrupp Logistik) (ehem. Trupp Log Fü)
- FGr Log-MW (Fachgruppe Logistik Materialwirtschaft) (ehem. Trupp Log M)
- FGr Log-V (Fachgruppe Logistik-Verpflegung) (ehem. Trupp Log V)

**Comment by jonas-koeritz** [comment]
Dann wirds wohl langsam Zeit. Ich hoffe Ich komme die Tage mal dazu. Danke für den Hinweis!

**Comment by dmth** [comment]
Hi @jonas-koeritz,

ich habe in meinem commit https://github.com/dmth/Taktische-Zeichen/commit/cb929c079662bfcc1500aeba596f1066aa1524b4 versucht die ersten Zeichen umzusetzen. Schau doch mal drüber. Wenn's passt mache ich gerne einen PR fertig.

**Comment by dmth** [comment]
Hi @jonas-koeritz hast du jetzt Zeichen aus meinem Repo kopiert und neu commitet? Wäre das nicht mit einem PR von mir einfacher gegangen (und hätte mich als contributor erhalten)?

**Comment by jonas-koeritz** [comment]
Ich habe nicht alle 1:1 übernommen und hab das Cherry-Picking nicht auf die Reihe bekommen 🙄.
Vorschlag zur Güte die Metadaten bekommen ein "author" Feld, da kannst du dich dann in den Zeichen jeweils per PR verewigen.

Wie der Header konkret aussehen wird lege ich in den nächsten Tagen mal "fest" als ersten Entwurf.

**Comment by dmth** [comment]
Hi, mach dir keinen Stress. Mein Kommentar liest sich fieser als es gemeint war, merke ich gerade.
