### ISSUE TITLE
THW-Fachgruppen ohne Typ

### ISSUE THREAD

**Issue by KBreker** [jonas-koeritz/Taktische-Zeichen#86]
Ahoi!

Bei einigen Fachgruppen hast Du taktische Zeichen erstellt, die keinen Fachgruppen-Typ aufweisen. Das finde ich gut, weil dadurch auch die Fachgruppe als Sammelbegriff verwendet werden kann.

Leider machst Du das nicht durchgängig, so fehlen z.B. die Fachgruppen-Zeichen ohne Typ für die Öl, O, R, W.

Kannst Du die vielleicht ergänzen?

**Comment by jonas-koeritz** [comment]
Guter Hinweis, werden ergänzt!

KBreker <notifications@github.com> schrieb am Sa., 28. Nov. 2020, 10:54:
