### ISSUE TITLE
Einheitliche Dateinamenstruktur

### ISSUE THREAD

**Issue by KBreker** [jonas-koeritz/Taktische-Zeichen#87]
Ahoi!

Bei den Dateinamen hast Du leider kein einheitliches System:

FGr_FK_Fernmeldetrupp.svg
FGr_FK_Führungstrupp.svg
FGr_FK_Führungs_und_Kommunikationstrupp.svg
FGr_FK.svg
FGr_Führung-Kommunikation_A.svg
FGr_Führung-Kommunikation_B.svg

oder

FGr_Wasserschaden-Pumpen.svg
FGr_WP_A.svg
FGr_WP_B.svg
FGr_WP_C.svg

Wäre da eine Anpassung möglich? ;-)

**Comment by jonas-koeritz** [comment]
Auch guter Einwand, wird korrigiert.

KBreker <notifications@github.com> schrieb am Sa., 28. Nov. 2020, 10:56:
