### ISSUE TITLE
Fachzug Führung-Kommunikation

### ISSUE THREAD

**Issue by KBreker** [jonas-koeritz/Taktische-Zeichen#89]
Ahoi!

Analog zum Fachzug Logistik müsste noch der Fachzug Führung-Kommunikation ergänzt werden.

**Comment by dmth** [comment]
Hi, die STAN dazu ist noch nicht beschlossen, daher wäre das etwas vorausgegriffen.

**Comment by jonas-koeritz** [comment]
Solange das Zeichen sich logisch ergibt sehe ich da kein allzu großes Problem, da manchmal das System ein bisschen "gedehnt" wird würde ich aber auch ein bisschen abwarten. Die Ergänzung geht dann ja schnell.

Wenn die Metadaten für die Zeichen im Header der SVG Daten enthalten sind kann man sich Gedanken machen über ein Feld das die zugrundeliegende Norm angibt. In diesem Fall würde dann eben die zukünftige Norm angegeben sein.
