### ISSUE TITLE
Lizenz GitHub-Konform ablegen

### ISSUE THREAD

**Issue by jonas-koeritz** [jonas-koeritz/Taktische-Zeichen#90]
Unter License zeigt die GitHub App aktuell nur "Other" an.

**Comment by dmth** [comment]
Auch die Webseite sagt hier nicht "Apache License" sondern nur "View License". 
Die Github Hilfe sagt dazu, dass eine Lizenz aus einem Lizenz-Template erzeugt werden soll vgl.: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository.

Ggfs wird das aktuelle Dokument nicht erkannt, da es sich in Zeile 1 vom Template unterschiedet. Die Notiz "Copyright By" gehört dann in die Source-Files und nicht ins LICENSE Files.

**Comment by dmth** [comment]
Ich habe das in meinem Repo mal getestet. https://github.com/dmth/Taktische-Zeichen so richtig scheint das aber auch nicht zu funktionieren. Als License wird bei mir dennoch "View License" angezeigt und nicht "Apache 2.0 License". Hier würde ich Apache 2.0 License erwarten, da in meinem anderen Repos auch konkret der Lizenzname genannt wird (z.B. MIT).

**Comment by real-or-random** [comment]
Ich hab mir das mal genauer angesehen.

> Ich habe das in meinem Repo mal getestet. [dmth/Taktische-Zeichen](https://github.com/dmth/Taktische-Zeichen) so richtig scheint das aber auch nicht zu funktionieren. Als License wird bei mir dennoch "View License" angezeigt und nicht "Apache 2.0 License". Hier würde ich Apache 2.0 License erwarten, da in meinem anderen Repos auch konkret der Lizenzname genannt wird (z.B. MIT).

Das liegt daran, dass noch eine COPYRIGHT.md existiert. (Und wahrscheinlich auch daran, dass dein Test nicht auf dem master branch war:
https://github.com/real-or-random/Taktische-Zeichen

Ich habe auch gerade https://github.com/jonas-koeritz/Taktische-Zeichen#lizenz gelesen und wäre dafür den Absatz vollständig zu entfernen. All das ist doch schon in der Lizenz geregelt.

> Die Zeichen können im Rahmen der Apache License 2.0 verwendet werden

Und der Code?

> Die Datei COPYRIGHT.md darf nur durch Angaben über eigene Änderungen erweitert werden.

Warum brauchst du die Datei? Überhaupt braucht man keine Copyright Notice, auch in den USA nicht mehr. https://opensource.com/article/20/10/copyright-notices-open-source-software

> Die Datei NOTICE muss in jeder Kopie unverändert beibehalten werden.

Das steht in der Lizenz aber anders: "You may add Your own notices within Derivative Works that You distribute, alongside or as an addendum to the NOTICE text from the Work"

> Die Kommerzielle Nutzung ist gestattet, sofern die Copyright Hinweise für den Benutzer klar ersichtlich sind, d.h. der Vollständige Inhalt der Datei COPYRIGHT.md muss über die Benutzeroberfläche (bei Anwendungen mit grafischer Benutzeroberfläche) oder im Programmverzeichnis (für Anwendungen ohne grafische Benutzeroberfläche) für jeden Benutzer einsehbar sein.

Das steht in der Lizenz anders.  Die erlaubt die kommerzielle Nutzung auch. Da steht höchstens, dass man die NOTICE weitergeben muss, nicht die COPYRIGHT.md. Da wird die strenge Unterscheidung zwischen Arten der Anwendung gar nicht gemacht. Zum Beispiel ist immer erlaubt "within a NOTICE text file distributed           as part of the Derivative Works" und das reicht aus.

Deine Formulierung könnte man außerdem dahingehend verstehen, dass man das die Datei nur bei kommerziellen aber nicht bei nicht-kommerziellen Nutzungen weitergeben muss.

Kurzum: Der Text ist entweder überflüssig oder widerspricht der Lizenz. Damit riskiert man, dass Teile oder die ganze Lizenz hinfällig und wirksam werden. 

Mein Vorschlag wäre, den Absatz und vielleicht auch die NOTICE vollständig entfernen.

Das Problem ist, dass das jetzt doch unter Umständen ja schon irgendwie Lizenzänderung. Noch wäre die Anzahl der Leute ja überschaubar...

Wenn ich ehrlich bin, finde ich die gewählte Lizenz auch nicht sonderlich zweckmäßig. Du hast mal zur Font mal gesagt, dass die gewählt wurde, so dass die Benutzer sich um rechtliche Fragen keine Gedanken machen müssen. Hier müssen sie das leider. Wenn ich zum Beispiel im Einsatz schnell ein neues Zeichen erstelle (z. B. indem ich ein paar Buchstaben austausche) und das dann an Kollegen per E-Mail schicke, muss ich dann die NOTICE mitschicken und die COPYRIGHT.md? Vielleicht. Wahrscheinlich wird es niemanden interessieren. Aber praktisch ist das jedenfalls nicht. Und wenn dann Fotos von der Lagekarte gemacht werden, müssen die dann die NOTICE beinhalten? Wahrscheinlich nicht. ;) Aber ich denke, der Zweck der Lizenz sollte sein, dass die Fragen eben unproblematisch und einfach geklärt sind.

Die Zeichen sind auch eigentlich nicht wirklich Source Code, also wäre eine CC-Lizenz passender. Ich glaube, ich fände ich die extreme Wahl CC0 bei solchen (letztendlich simplen) Zeichen eigentlich wesentlich passender und angenehmer für den Benutzer. Auch ist nicht ganz klar ist, ob die Schöpfungshöhe eines blauen Rechtecks mit zwei Punkten und dem Buchtaben "W" groß genug ist um überhaupt urheberrechtlichen Schutz zu genießen. Dann könnte immer noch die Sammlung und systematische Aufbereitung der vielen Zeichen geschützt sein (https://de.wikipedia.org/wiki/Datenbankwerk). Also wenn dir was daran liegt, dass der Name genannt wird, dann kümmern sich die CC-Lizenzen wie CC BY oder CC BY-SA darum wesentlich besser.

Für das bisschen echten Code im Repo kann man dann auch eine andere Lizenz wählen, siehe auch https://choosealicense.com/non-software/ für ein Beispiel für einen solchen Mix.

**Comment by jonas-koeritz** [comment]
Das nenne Ich mal eine umfangreiche und umfassende Antwort zu dem Thema.
Die Auswahl der Lizenz habe Ich ehrlich gesagt relativ kurzfristig und ohne
große Hintergedanken anhand irgendeiner Matrix gemacht.
CC BY-(SA) erscheint mit im Nachhinein dem Geist des ganzen mehr zu
entsprechen.
Da werde ich mich mal drum kümmern.

Tim Ruffing <notifications@github.com> schrieb am Di., 16. Feb. 2021, 11:02:

**Comment by jonas-koeritz** [comment]
Die Lizenz ist angepasst, GitHub kennt die CC-BY aber nicht.

**Comment by jonas-koeritz** [comment]
Kaum macht mans richtig funktionierts dann doch.

**Comment by dmth** [comment]
Das klingt nach einer ordentlichen Lösung. CC-BY ist für mich ok.
