### ISSUE TITLE
Kreise und Zeiger für Schadenskonten

### ISSUE THREAD

**Issue by Daugl** [jonas-koeritz/Taktische-Zeichen#96]
Für die Schadenskonten, wie sie z.B. in der Fgr FK beim THW verwendet werden, vermisse ich die nummerierten Zeiger und Kreise.
Der Standardsatz numeriert von 1-20 jeweils mit den Farben weiß, gelb und rot.

Beispiele:
![ew8](https://user-images.githubusercontent.com/47792865/103229877-47ffb700-4934-11eb-9c45-ef8696fd614a.png)
![dw8](https://user-images.githubusercontent.com/47792865/103229883-49c97a80-4934-11eb-865e-240983b45b8d.png)
![dg0](https://user-images.githubusercontent.com/47792865/103229880-4930e400-4934-11eb-9c84-41d227c8ca6e.png)
![eg0](https://user-images.githubusercontent.com/47792865/103229885-4a621100-4934-11eb-81fd-9e64c666c40f.png)
![dg4](https://user-images.githubusercontent.com/47792865/103229881-4930e400-4934-11eb-880a-a239d0d2a6cc.png)
![eg4](https://user-images.githubusercontent.com/47792865/103229887-4afaa780-4934-11eb-93b6-9a6748c4768a.png)
![dr2](https://user-images.githubusercontent.com/47792865/103229882-49c97a80-4934-11eb-8c07-c543ae6bf97b.png)
![er2](https://user-images.githubusercontent.com/47792865/103229888-4afaa780-4934-11eb-9c01-180299375f6a.png)

**Comment by jonas-koeritz** [comment]
Gute Idee!
