### ISSUE TITLE
Text an falscher Position in Firefox

### ISSUE THREAD

**Issue by real-or-random** [jonas-koeritz/Taktische-Zeichen#99]
![Screenshot from 2021-01-13 15-43-38](https://user-images.githubusercontent.com/1071625/104467126-41b93e00-55b6-11eb-84a2-89982bd31c6d.png)

Firefox 84.0.2

**Comment by jonas-koeritz** [comment]
Hi, danke für die Meldung. Das Problem ist bekannt. Firefox unterstützt ein paar Attribute nicht und die müssen ersetzt werden.
